### PR TITLE
Refact: use internal instance of mongoose and export it

### PR DESCRIPTION
**Pull request by rodrigo4244**
This PR is to refactor `@invisible/mongoose` module to export an instance of `mongoose`.

### CODE REVIEW

**Comment by rodrigo4244** [comment]
This is the PR being used on: https://github.com/invisible-tech/gear/pull/4 and on https://github.com/invisible-tech/gear/tree/staging

**Comment by gunar** [comment]
Looks good to me. I added a fix, please check whether I got it right.
I would prefer not to export both `dbConnection` and `getConnection`, seems confusing.
Also, as `dbConnection` is a function, should it be called something else? (something like `getConnection`, for example haha).

**Comment by rodrigo4244** [comment]
You got it right! I called on the event handlers but forgot to call that one on `dbShutdown`. Thanks!

**Comment by rodrigo4244** [comment]
I removed `@invisible/logger` dependency and `dbConnection`, the latter because it would be redundant since we have `getConnection` already.

**Pull request merged**
